// <auto-generated />
using System;
using AubgEMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AubgEMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023122005_AddUniqueIndex_Attendance_EventUser")]
    partial class AddUniqueIndex_Attendance_EventUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            Description = "Entrepreneurship & innovation hub",
                            Name = "The Hub AUBG",
                            OrganizerId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 3,
                            Description = "Student-led investing",
                            Name = "Investment Management Club",
                            OrganizerId = "dea12856-c198-4129-b3f3-b893d8395082"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Business Club AUBG",
                            OrganizerId = "dea12856-c198-4129-b3f3-b893d8395082"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 10,
                            Name = "MEU AUBG",
                            OrganizerId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 11,
                            Name = "Other",
                            OrganizerId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9"
                        });
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Business Department"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computer Science Department"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Economics Department"
                        },
                        new
                        {
                            Id = 4,
                            Name = "History and Civilizations Department"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Journalism, Media, and Communication Department"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Literature and Theater Department"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mathematics and Science Department"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Modern Languages and Arts Department"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Philosophy and Psychology Department"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Politics and European Studies Department"
                        },
                        new
                        {
                            Id = 11,
                            Name = "University-wide (Independent Clubs)"
                        });
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 200,
                            ClubId = 1,
                            Description = "The Welcome Fair is one of the most anticipated events of the semester, bringing together all student clubs and organizations under one roof. Students have the chance to explore the different opportunities AUBG offers beyond academics, from entrepreneurship and debating to sports and arts. The event is designed to showcase the diverse extracurricular activities available and to encourage newcomers to join and become active members of the community. Informational booths, short presentations, and networking opportunities make this fair both informative and exciting, setting the tone for an engaging and dynamic academic year ahead.",
                            EventTypeId = 4,
                            ImageUrl = "https://www.aubg.edu/wp-content/uploads/2024/09/DSC07164-1.jpg",
                            LocationId = 23,
                            OrganizerId = "dea12856-c198-4129-b3f3-b893d8395082",
                            StartTime = new DateTime(2025, 10, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome Fair"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 150,
                            ClubId = 2,
                            Description = "This introductory session on Artificial Intelligence aims to provide students from all backgrounds with a comprehensive overview of what AI is, how it works, and why it matters. The lecture will cover the basics of machine learning, neural networks, and everyday AI applications, while also addressing the ethical concerns surrounding automation and data usage. It is an open and beginner-friendly talk designed to spark curiosity and inspire further exploration in the field. The event will conclude with an interactive Q&A session where attendees can discuss potential projects, research ideas, and applications of AI in real-world contexts.",
                            EventTypeId = 3,
                            ImageUrl = "https://aubgdaily.com/wp-content/uploads/2017/03/Optimized-_DSC1111.jpg",
                            LocationId = 1,
                            OrganizerId = "dea12856-c198-4129-b3f3-b893d8395082",
                            StartTime = new DateTime(2025, 10, 5, 18, 30, 0, 0, DateTimeKind.Utc),
                            Title = "AI 101: Intro Talk"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 120,
                            ClubId = 1,
                            Description = "Pitch Night is the ultimate stage for students with entrepreneurial ambitions to present their innovative ideas before a panel of faculty, alumni, and external experts. Each team will have a limited time to pitch their concept, explain the problem it solves, and highlight its market potential. The event is not only a competition but also an opportunity for mentorship and constructive feedback. Even teams that don’t win will walk away with valuable insights to refine their ideas. Pitch Night fosters creativity, teamwork, and problem-solving skills while also connecting aspiring entrepreneurs with potential investors and collaborators within the AUBG network.",
                            EventTypeId = 1,
                            ImageUrl = "https://www.aubg.edu/wp-content/uploads/2023/05/Elevate-The-Recursive.jpg",
                            LocationId = 14,
                            OrganizerId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9",
                            StartTime = new DateTime(2025, 10, 12, 19, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pitch Night"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 100,
                            ClubId = 3,
                            Description = "The Case Study Challenge is a team-based competition where participants are given a real-world business scenario and tasked with developing practical, data-driven solutions under time constraints. Teams will analyze the problem, brainstorm strategies, and present their solutions to a panel of judges composed of professors and industry professionals. The challenge pushes students to apply classroom knowledge in a fast-paced and highly collaborative environment. It promotes critical thinking, communication, and decision-making skills, while also exposing participants to real issues faced by modern businesses. Whether winning or not, all teams gain experience that is invaluable for future academic and career pursuits.",
                            EventTypeId = 5,
                            ImageUrl = "https://aubgbusinessclub.com/wp-content/uploads/2022/11/Web-59-1-scaled.jpg",
                            LocationId = 15,
                            OrganizerId = "dea12856-c198-4129-b3f3-b893d8395082",
                            StartTime = new DateTime(2025, 10, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Case Study Challenge"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 180,
                            ClubId = 4,
                            Description = "The Model European Union (MEU) Simulation Conference is a multi-day event designed to replicate the workings of European institutions. Students will take on the roles of parliament members, ministers, or diplomats and engage in debates, negotiations, and policy-making activities. The simulation provides a unique, immersive experience that combines academic knowledge with practical diplomatic skills. Participants will prepare resolutions, argue positions, and attempt to build consensus in a politically diverse environment. It is both intellectually stimulating and socially engaging, as students interact with peers from different disciplines while exploring complex issues that mirror the challenges faced by policymakers today.",
                            EventTypeId = 10,
                            ImageUrl = "https://www.aubg.edu/wp-content/uploads/2025/04/AUBG-Today-Hero-Image-3.jpg",
                            LocationId = 25,
                            OrganizerId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9",
                            StartTime = new DateTime(2025, 10, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "MEU Simulation Conference"
                        });
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.EventAttendance", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("EventAttendances");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lecture"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Meeting"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Challenge"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Theatre Performance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dance Performance"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Movie Screening"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Video Shooting"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Concert"
                        });
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 100,
                            Name = "BAC Auditorium"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 36,
                            Name = "BAC Room 001"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            Name = "BAC Room 002"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 33,
                            Name = "BAC Room 003"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 39,
                            Name = "BAC Room 004"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 24,
                            Name = "BAC Room 101"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 26,
                            Name = "BAC Room 103"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 25,
                            Name = "BAC Room 201"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 39,
                            Name = "BAC Room 202"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 41,
                            Name = "BAC Room 203"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 33,
                            Name = "BAC Room 204"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 24,
                            Name = "BAC Room 206"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 14,
                            Name = "BAC Room 207"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 50,
                            Name = "Panitza Library"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 300,
                            Name = "Dr. Carl Djerassi Theater Hall "
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 200,
                            Name = "Sports Hall"
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 30,
                            Name = "Aspire"
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 50,
                            Name = "Ground Floor Lobby"
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 30,
                            Name = "6306 - Board Room"
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 30,
                            Name = "6307 - Postbank Room"
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 40,
                            Name = "6307 - Restaurant"
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 20,
                            Name = "6307 - Café"
                        },
                        new
                        {
                            Id = 23,
                            Capacity = 108,
                            Name = "MB Auditorium"
                        },
                        new
                        {
                            Id = 24,
                            Capacity = 40,
                            Name = "Skaptopara I MPR"
                        },
                        new
                        {
                            Id = 25,
                            Capacity = 40,
                            Name = "Skaptopara II MPR"
                        },
                        new
                        {
                            Id = 26,
                            Capacity = 40,
                            Name = "Skaptopara III MPR"
                        },
                        new
                        {
                            Id = 27,
                            Capacity = 40,
                            Name = "Outdoors"
                        });
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("NewsPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "The academic year has officially begun, and the campus is buzzing with energy as students return. From classes to social events, there’s something for everyone. The Semester Kickoff marks the start of a new journey filled with opportunities, challenges, and experiences that will shape the year ahead.",
                            CreatedAt = new DateTime(2025, 9, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://www.aubg.edu/wp-content/uploads/2022/05/about-hero-bg.jpg",
                            Title = "Semester Kickoff"
                        },
                        new
                        {
                            Id = 2,
                            Body = "This week marks the start of club recruitment, where students can sign up for organizations that match their passions and interests. Whether you’re into finance, debating, arts, or volunteering, there’s a place for you. Recruitment Week is the best time to connect with peers and discover your community.",
                            CreatedAt = new DateTime(2025, 9, 18, 9, 30, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://iee.bg/wp-content/uploads/2023/08/DSC02107-1-2-scaled.jpg",
                            Title = "Clubs Recruitment Week"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Applications are now open for Pitch Night, the signature event where students showcase innovative startup ideas. Teams will compete for recognition and prizes, while gaining valuable feedback from mentors and judges. Don’t miss your chance to present your project and take the first step toward entrepreneurial success.",
                            CreatedAt = new DateTime(2025, 9, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://www.aubg.edu/wp-content/uploads/2022/05/students-life-hero.jpg",
                            Title = "Pitch Night Applications Open"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6a3f8c34-3e7d-4b11-9d4f-aaa000000001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "6a3f8c34-3e7d-4b11-9d4f-aaa000000002",
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        },
                        new
                        {
                            Id = "6a3f8c34-3e7d-4b11-9d4f-aaa000000003",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38bedbc3-c55b-425e-b88d-a6a8bfa8ebd1",
                            Email = "admin@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBicF6pkhY2uZFzv76Kzl2D0jhO7tvKDFo9/X5cvDCChY49D70cEPHLbC3VJy6miWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "018f74e9-396d-43ce-b5af-4d3ac2fc4954",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        },
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8db5992-ece6-4314-9756-2c372081a79e",
                            Email = "organizer@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ORGANIZER@MAIL.COM",
                            NormalizedUserName = "ORGANIZER@MAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzjspw0AIeG6MNjGTD6W9tqeEXD4lGXqDqJusG2+GpEoizkOIF1oW/9qfEgjHGILw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "391ed893-0c0a-4aa3-8aaa-2e6e7f9e541a",
                            TwoFactorEnabled = false,
                            UserName = "organizer@mail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "eb9175e5-1e90-4a71-b89e-a1ee5d0cc9e9",
                            RoleId = "6a3f8c34-3e7d-4b11-9d4f-aaa000000001"
                        },
                        new
                        {
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082",
                            RoleId = "6a3f8c34-3e7d-4b11-9d4f-aaa000000002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Club", b =>
                {
                    b.HasOne("AubgEMS.Infrastructure.Data.Models.Department", "Department")
                        .WithMany("Clubs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Event", b =>
                {
                    b.HasOne("AubgEMS.Infrastructure.Data.Models.Club", "Club")
                        .WithMany("Events")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AubgEMS.Infrastructure.Data.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AubgEMS.Infrastructure.Data.Models.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("EventType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.EventAttendance", b =>
                {
                    b.HasOne("AubgEMS.Infrastructure.Data.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Club", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Department", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AubgEMS.Infrastructure.Data.Models.Location", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
